version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin4-local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
