// Code generated by mockery v2.42.0. DO NOT EDIT.

package usecase

import (
	context "context"
	models "tinder-cloning/models"

	mock "github.com/stretchr/testify/mock"

	schema "tinder-cloning/services/membership/schema"

	sql "database/sql"
)

// MockMembershipUseCase is an autogenerated mock type for the MembershipUseCase type
type MockMembershipUseCase struct {
	mock.Mock
}

// CreateOne provides a mock function with given fields: ctx, sqlTx, data
func (_m *MockMembershipUseCase) CreateOne(ctx context.Context, sqlTx *sql.Tx, data *models.Membership) (*sql.Tx, error) {
	ret := _m.Called(ctx, sqlTx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateOne")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, *models.Membership) (*sql.Tx, error)); ok {
		return rf(ctx, sqlTx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, *models.Membership) *sql.Tx); ok {
		r0 = rf(ctx, sqlTx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, *models.Membership) error); ok {
		r1 = rf(ctx, sqlTx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeatureMembership provides a mock function with given fields: ctx, accountID
func (_m *MockMembershipUseCase) GetFeatureMembership(ctx context.Context, accountID string) (*schema.FeatureMembership, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetFeatureMembership")
	}

	var r0 *schema.FeatureMembership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*schema.FeatureMembership, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *schema.FeatureMembership); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.FeatureMembership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMembershipUseCase creates a new instance of MockMembershipUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMembershipUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMembershipUseCase {
	mock := &MockMembershipUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
